sonarqube:
  image: sonarqube:5.1
  ports:
  - "9000:9000"
  - "9092:9092"
jenkinscore:
  build: jenkins/jenkinscore

standardjenkins:
  build: jenkins
  ports:
  - "8080:8080"
  - "5000:5000"
  links:
  - sonarqube
  volumes:
  - jenkins/volume_test:/var/jenkins_home
  environment:
  - JAVA_HOME=/usr/lib/jvm/default-java
  - MAVEN_HOME=/usr/share/maven
  - SONAR_RUNNER_VERSION=2.4
