jenkinscore:
  build: jenkins/jenkinscore
  command: shutdown -h now
jenkins:
  build: jenkins
  ports:
  - "8080:8080"
  - "5000:5000"
  links:
  - sonarqube:sonarqube
  - postgresql:sonardb
  environment:
  - SONARQUBE_JDBC_USERNAME=admin
  - SONARQUBE_JDBC_PASSWORD=admin
  volumes:
  - ./jenkins/jenkins_home:/var/jenkins_home
sonarqube:
  build: sonar
  ports:
  - "9000:9000"
  environment:
  - SONARQUBE_JDBC_USERNAME=admin
  - SONARQUBE_JDBC_PASSWORD=admin
  links:
  - postgresql:db
  volumes:
  - ./sonarqube/sonarqube/data:/opt/sonarqube/data
  - ./sonarqube/sonarqube/extensions:/opt/sonarqube/extensions
postgresql:
  image: postgres:9.3
  ports:
  - "5432:5432"
  environment:
  - POSTGRES_USER=admin
  - POSTGRES_PASSWORD=admin
  - POSTGRES_DB=sonar
  volumes:
  - ./postgres/postgres/data:/var/lib/postgresql/data